name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/Admin_Settings_Male.svg
    - assets/icons/Commercial.svg
    - assets/icons/Connected_People.svg
    - assets/icons/End.svg
    - assets/icons/Expand_Arrow.svg  
    - assets/icons/Favorite.svg
    - assets/icons/Feed_Paper.svg
    - assets/icons/Home_Page.svg
    - assets/icons/logo.svg
    - assets/icons/Full_Stop.svg
    - assets/icons/Heart.svg
    - assets/icons/Music_Library.svg
    - assets/icons/Pause.svg
    - assets/icons/Plus.svg
    - assets/icons/Radar.svg
    - assets/icons/Search.svg
    - assets/icons/Settings.svg
    - assets/icons/Skip_to_Start.svg
    - assets/icons/Stage.svg
    - assets/icons/User.svg
    - assets/icons/Vector.svg